// ═══════════════════════════════════════════════════════════════
// AMP v2 — PE Bolt-On / Roll-Up Lenses
// ═══════════════════════════════════════════════════════════════

export const BOLT_ON_LENSES = [
  {
    gateCode: "G1",
    dimensionName: "Cross-Sell Opportunity",
    name: "Platform Synergy Mapping",
    framework: "Revenue Synergy Sizing",
    guidance: "Map every product and service offered by the bolt-on against the platform's existing customer base. For each overlap, estimate the addressable revenue opportunity and the probability of conversion. Focus on accounts where the platform already has a commercial relationship and the bolt-on's offering fills a documented need.",
    keyQuestions: [
      "How many of the platform's top 50 customers currently purchase the bolt-on's service from a competitor?",
      "What is the annual spend at these overlapping accounts on the services the bolt-on provides?",
      "What conversion rate is realistic for cross-selling within the first 12 months?",
      "Are there contractual or competitive restrictions on cross-selling to existing accounts?",
    ],
    evidenceNeeds: ["Customer overlap matrix", "Platform customer spend analysis", "Bolt-on service catalog mapped to platform accounts"],
    calibrationAnchors: [
      { score: 10, label: ">$3M addressable cross-sell with 7+ identified overlapping accounts" },
      { score: 7, label: "$1M-$3M cross-sell with strong overlap and clear go-to-market path" },
      { score: 5, label: "$500K-$1M with moderate overlap" },
      { score: 3, label: "<$500K or unvalidated assumptions" },
      { score: 0, label: "No customer overlap; cross-sell requires new market development" },
    ],
    blindSpots: [
      "Cross-sell models rarely account for sales cycle length or relationship friction when introducing new vendors to existing accounts",
      "Assumes platform sales team has capacity and incentive alignment to sell bolt-on's services",
    ],
    isDefault: true,
    source: "alio_foundry",
  },
  {
    gateCode: "G1",
    dimensionName: "Capability Gap Fill",
    name: "Build vs. Buy for Platform",
    framework: "Organic Build Cost Comparison",
    guidance: "Compare the cost and timeline of organically building the capability the bolt-on provides versus acquiring it. Include: hiring costs, technology development, time-to-market, opportunity cost of delayed capability, and risk of organic build failure. The bolt-on is justified only if acquisition delivers faster, cheaper, or lower-risk capability fill.",
    keyQuestions: [
      "What would it cost to build this capability organically over 24 months (headcount, technology, overhead)?",
      "How long would organic build take to reach the bolt-on's current capability level?",
      "What revenue is at risk during the organic build period that the bolt-on would capture immediately?",
      "Has the platform attempted to build this capability before? What happened?",
    ],
    evidenceNeeds: ["Organic build cost estimate", "Capability gap matrix", "Prior organic build attempts (if any)"],
    calibrationAnchors: [
      { score: 10, label: "Bolt-on delivers capability 18+ months faster at <50% of organic build cost" },
      { score: 7, label: "Bolt-on is meaningfully faster or cheaper than organic build" },
      { score: 5, label: "Build vs. buy is roughly equivalent — bolt-on justified by speed" },
      { score: 3, label: "Organic build is feasible and may be cheaper" },
      { score: 0, label: "Organic build is clearly preferable — bolt-on premium not justified" },
    ],
    blindSpots: [
      "Build cost estimates are typically 50-100% too low and timelines 2x too optimistic",
      "Does not account for integration risk — acquired capability may degrade during integration",
    ],
    isDefault: true,
    source: "alio_foundry",
  },
  {
    gateCode: "G4",
    dimensionName: "Synergy-Adjusted Returns",
    name: "Accretion Analysis",
    framework: "Portfolio EBITDA Accretion",
    guidance: "Calculate whether the bolt-on is accretive or dilutive to the platform's aggregate financial metrics. Compare the implied acquisition multiple to the platform's current valuation multiple. If the bolt-on is acquired at a lower multiple, it's immediately accretive to the portfolio. Factor in synergies to compute the synergy-adjusted effective multiple.",
    keyQuestions: [
      "What is the platform's current aggregate EBITDA multiple (implied by fund valuation)?",
      "At what multiple is the bolt-on being acquired?",
      "What is the synergy-adjusted effective multiple (purchase price minus PV of synergies)?",
      "How does this acquisition change the platform's aggregate growth rate and margin profile?",
    ],
    evidenceNeeds: ["Platform valuation summary", "Bolt-on entry multiple analysis", "Synergy-adjusted multiple calculation"],
    calibrationAnchors: [
      { score: 10, label: "Immediately accretive by >1x EBITDA turn; synergy-adjusted multiple <5x" },
      { score: 7, label: "Accretive on synergy case; effective multiple below platform average" },
      { score: 5, label: "Neutral — entry multiple matches platform; synergies provide modest uplift" },
      { score: 3, label: "Dilutive without synergies; requires full synergy capture to justify" },
      { score: 0, label: "Dilutive even with aggressive synergy assumptions" },
    ],
    blindSpots: [
      "Accretion analysis assumes stable platform valuation — market multiples can compress",
      "Does not account for integration costs that temporarily reduce combined EBITDA",
    ],
    isDefault: true,
    source: "alio_foundry",
  },
  {
    gateCode: "G4",
    dimensionName: "Valuation Attractiveness",
    name: "Synergy-Adjusted Multiple",
    framework: "Effective Purchase Price Analysis",
    guidance: "Calculate the effective purchase price after subtracting the present value of identified synergies. This reveals the 'real' price the platform is paying for the standalone business. Compare this effective multiple to comparable bolt-on transactions in the sector.",
    keyQuestions: [
      "What is the total enterprise value at the proposed purchase price?",
      "What is the PV of identified cost synergies (discount rate = WACC)?",
      "What is the PV of identified revenue synergies (risk-adjusted at 50% haircut)?",
      "What is the effective multiple after synergy credit? How does it compare to precedent bolt-on transactions?",
    ],
    evidenceNeeds: ["Synergy model with PV calculations", "Precedent transaction comps for bolt-ons", "Sensitivity table on synergy realization %"],
    calibrationAnchors: [
      { score: 10, label: "Effective multiple <4x after synergy credit — exceptional value" },
      { score: 7, label: "Effective multiple 4-6x — strong value with reasonable synergy assumptions" },
      { score: 5, label: "Effective multiple 6-8x — fair value requiring synergy execution" },
      { score: 3, label: "Effective multiple 8-10x — premium price, synergy-dependent" },
      { score: 0, label: "Effective multiple >10x — overpaying even with full synergy credit" },
    ],
    blindSpots: [
      "Synergy PV calculations are highly sensitive to discount rate and realization timeline assumptions",
      "Revenue synergies are notoriously harder to capture than cost synergies — haircut may need to be >50%",
    ],
    isDefault: true,
    source: "alio_foundry",
  },
  {
    gateCode: "G5",
    dimensionName: "Systems Integration",
    name: "Integration Playbook Fit",
    framework: "Playbook Compatibility Assessment",
    guidance: "Assess whether the platform's proven integration playbook (developed from prior bolt-ons) can be applied to this target. Playbook fit is the single best predictor of successful integration. Score higher when the integration follows a pattern the team has executed before.",
    keyQuestions: [
      "How many prior bolt-ons has the platform successfully integrated using the current playbook?",
      "What percentage of this bolt-on's systems, processes, and operations match the playbook's scope?",
      "What are the material differences from prior integrations that require playbook modifications?",
      "Does the integration team include members who have executed the playbook on prior bolt-ons?",
    ],
    evidenceNeeds: ["Integration playbook (current version)", "Prior bolt-on integration retrospectives", "Gap analysis vs. playbook scope"],
    calibrationAnchors: [
      { score: 10, label: "Playbook covers >90% of integration scope; team has executed 3+ times" },
      { score: 7, label: "Playbook covers 70-90%; minor modifications needed" },
      { score: 5, label: "Playbook covers 50-70%; material modifications required" },
      { score: 3, label: "Playbook covers <50%; effectively a custom integration" },
      { score: 0, label: "No applicable playbook — first-of-kind integration for the platform" },
    ],
    blindSpots: [
      "Playbook fit can create false confidence — each business is unique despite structural similarities",
      "Prior integration success may not scale if team members have departed",
    ],
    isDefault: true,
    source: "alio_foundry",
  },
  {
    gateCode: "G5",
    dimensionName: "Synergy Capture Plan",
    name: "100-Day Plan Assessment",
    framework: "Integration Execution Readiness",
    guidance: "Evaluate the quality and feasibility of the 100-day integration plan. A credible plan has named workstream owners, specific milestones with dates, synergy line items with dollar targets, and escalation triggers. Plans without these elements are aspirational, not executable.",
    keyQuestions: [
      "Does every synergy line item have a named owner, dollar target, and achievement date?",
      "Are the first 30 days focused on 'quick wins' that build integration momentum?",
      "What is the escalation protocol when a workstream falls behind plan?",
      "How does the plan account for ongoing business operations during integration?",
    ],
    evidenceNeeds: ["100-day integration plan (detailed)", "Workstream owner assignments", "Prior bolt-on integration post-mortems"],
    calibrationAnchors: [
      { score: 10, label: "Detailed plan with all elements; team briefed; lessons from prior integrations incorporated" },
      { score: 7, label: "Solid plan with most elements; minor gaps in owner assignments" },
      { score: 5, label: "High-level plan exists; workstreams identified but not yet staffed" },
      { score: 3, label: "Outline only; no workstream owners or specific milestones" },
      { score: 0, label: "No integration plan prepared" },
    ],
    blindSpots: [
      "100-day plans often underestimate 'business as usual' operational demands during integration",
      "Plan quality does not predict execution quality — team capability and bandwidth are the real constraints",
    ],
    isDefault: true,
    source: "alio_foundry",
  },
  {
    gateCode: "G6",
    dimensionName: "Founder Transition Risk",
    name: "Earnout Structure Analysis",
    framework: "Retention Mechanism Design",
    guidance: "Evaluate whether the proposed earnout and employment agreement structure effectively retains the founder through the critical integration period. Earnouts should align founder economics with integration success, not just revenue maintenance. Poorly structured earnouts create perverse incentives.",
    keyQuestions: [
      "Is the earnout tied to synergy milestones or just standalone revenue/EBITDA targets?",
      "What percentage of total consideration is at-risk via earnout?",
      "Does the employment agreement include non-compete, non-solicit, and IP assignment?",
      "What happens to the earnout if the founder departs early (clawback, acceleration, forfeiture)?",
    ],
    evidenceNeeds: ["Draft earnout term sheet", "Employment agreement summary", "Earnout scenario analysis"],
    calibrationAnchors: [
      { score: 10, label: "Earnout structure perfectly aligns founder incentives with integration success; robust clawback provisions" },
      { score: 7, label: "Well-structured earnout with reasonable synergy milestones; standard employment terms" },
      { score: 5, label: "Earnout exists but tied to standalone metrics, not integration success" },
      { score: 3, label: "Minimal earnout; founder retention depends on goodwill, not economic alignment" },
      { score: 0, label: "No earnout or employment agreement; founder retention is not secured" },
    ],
    blindSpots: [
      "Earnouts can create adversarial dynamics if milestones are perceived as unachievable",
      "Legal enforceability of non-competes varies significantly by jurisdiction",
    ],
    isDefault: true,
    source: "alio_foundry",
  },
  {
    gateCode: "G6",
    dimensionName: "Key Person Risk",
    name: "Knowledge Transfer Risk Assessment",
    framework: "Institutional Knowledge Documentation",
    guidance: "Assess the degree to which critical business knowledge is documented vs. held exclusively in the founder's or key persons' heads. Undocumented knowledge is the #1 source of value destruction in bolt-on integrations when key people depart.",
    keyQuestions: [
      "Are customer relationships documented (contacts, history, preferences) or held personally by the founder?",
      "Are operational processes documented (SOPs, quality standards, safety protocols) or tribal knowledge?",
      "Does the bolt-on have documented pricing logic, or does the founder set prices from experience?",
      "What happens to vendor relationships and supplier terms if the founder departs?",
    ],
    evidenceNeeds: ["Knowledge documentation inventory", "Key relationship mapping", "SOP documentation status"],
    calibrationAnchors: [
      { score: 10, label: "All critical knowledge documented; CRM populated; SOPs current; pricing formulaic" },
      { score: 7, label: "Most knowledge documented; some tribal knowledge but transferable via founder overlap" },
      { score: 5, label: "Partial documentation; meaningful tribal knowledge requiring 6-12 month transfer" },
      { score: 3, label: "Minimal documentation; most knowledge is in founder's head" },
      { score: 0, label: "No documentation; founder IS the knowledge base; departure = total loss" },
    ],
    blindSpots: [
      "Founders often overestimate how much knowledge is documented — verify with operational team, not just founder",
      "Documentation existence doesn't mean documentation quality — outdated SOPs are worse than no SOPs",
    ],
    isDefault: true,
    source: "alio_foundry",
  },
];
