// ═══════════════════════════════════════════════════════════════
// AMP v2 — Corporate Strategic Template
//
// For large corporate acquirers making strategic acquisitions.
// Strategic fit dominates over financial returns. Heavy weight
// on G1 (strategic alignment), G5 (organizational integration),
// and G6 (regulatory/antitrust risk).
// ═══════════════════════════════════════════════════════════════

export const CORPORATE_STRATEGIC_TEMPLATE = {
  name: "Corporate Strategic",
  slug: "corporate-strategic",
  archetype: "corporate",
  description: "Methodology for corporate M&A teams executing board-approved strategic acquisitions. Strategic fit and organizational integration take precedence over standalone financial returns.",
  version: "1.0.0",
  isPublished: true,
  isDefault: false,
  authoredBy: "Alio Foundry",
  changeLog: [{ version: "1.0.0", date: "2026-04-03", changes: ["Initial release"] }],

  personaSchema: {
    fields: [
      { key: "strategicJustification", label: "Strategic Rationale", required: true },
      { key: "coreBusinessRelevance", label: "Core Business Relevance (1-5)", required: true },
      { key: "integrationComplexity", label: "Expected Integration Complexity", required: true },
      { key: "regulatoryEnvironment", label: "Regulatory Scrutiny Level", required: true },
      { key: "publicCompany", label: "Acquirer is Public Company?", required: true },
    ],
  },

  weightPropagationRules: [
    { condition: "strategicJustification === 'Competitive Threat Denial'", gateCode: "G1", dimensionName: "Competitive Threat Assessment", adjustment: 20, reason: "Competitive denial thesis elevates urgency" },
    { condition: "regulatoryEnvironment === 'High'", gateCode: "G6", dimensionName: "Regulatory Approval Risk", adjustment: 25, reason: "High regulatory environment demands deeper diligence" },
    { condition: "integrationComplexity === 'Complex'", gateCode: "G5", dimensionName: "Cultural Integration Assessment", adjustment: 15, reason: "Complex integrations require deeper cultural due diligence" },
    { condition: "publicCompany === true", gateCode: "G6", dimensionName: "Regulatory Approval Risk", adjustment: 5, reason: "Public company acquirers face additional disclosure requirements" },
  ],

  gatesConfig: [
    {
      code: "G0", name: "Universe Qualification", purpose: "Hard filter: sector alignment, size, geography, and pre-screen for board strategic plan alignment and regulatory feasibility.", type: "binary", minimumScore: null, declineThreshold: null,
      rule: "ALL dimensions must pass. Any fail = remove from pipeline.",
      dimensions: [
        { name: "Sector Fit", weight: 20, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Target must operate in a sector aligned with the corporate strategic plan. Cross-reference the board's approved M&A mandate.", acceptanceParams: [{ label: "Sector Alignment", defaultValue: "Within board-approved acquisition sectors", type: "text" }] },
        { name: "Size Parameters", weight: 20, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Revenue and EV must fall within the approved acquisition size band. Too small = not needle-moving for a large corporate. Too large = requires board-level M&A committee approval.", acceptanceParams: [{ label: "Revenue Range", defaultValue: "$25M–$500M", type: "text" }, { label: "Max EV", defaultValue: "Per board delegation of authority", type: "text" }] },
        { name: "Board Strategic Plan Alignment", weight: 30, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Does this target appear in or directly support a named initiative in the board-approved strategic plan? Opportunistic acquisitions outside the plan require separate board approval.", acceptanceParams: [{ label: "Strategic Plan Reference", defaultValue: "Named initiative or strategic pillar", type: "text" }] },
        { name: "Regulatory Pre-Screen", weight: 30, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Pre-screen for obvious regulatory blockers: antitrust concentration, foreign investment restrictions (CFIUS/FDI), sector-specific regulations. If the deal would trigger HSR filing or face material regulatory delay, flag it here.", acceptanceParams: [{ label: "HSR Filing Required", defaultValue: "Assess if transaction exceeds HSR thresholds", type: "text" }, { label: "Regulatory Red Flags", defaultValue: "None identified (or specify)", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "strategic-plan-ref", label: "Board Strategic Plan Reference" }, { id: "regulatory-prescreen", label: "Regulatory Pre-Screen Memo" }],
    },
    {
      code: "G1", name: "Strategic Plan Alignment", purpose: "Deeply assess how this acquisition advances the corporate strategy. Strategic fit is the primary driver — financial returns are secondary.", type: "scored", minimumScore: 70, declineThreshold: 50,
      rule: "Weighted composite ≥70 to advance. This is the highest bar of any template — strategic acquisitions must be strongly justified.",
      dimensions: [
        { name: "Board Strategy Traceability", weight: 30, rubric: [{ score: 10, label: "Directly executes a board-approved strategic initiative with documented approval" }, { score: 7, label: "Strongly supports 1-2 strategic pillars with clear logic chain" }, { score: 5, label: "Moderate support — linked to strategy but not a named initiative" }, { score: 3, label: "Tangential — requires creative interpretation to connect to strategy" }, { score: 0, label: "No connection to board strategic plan" }], testGuidance: "Trace the acquisition rationale to specific pages/sections of the board strategic plan. Every strategic acquisition should have a direct line to an approved initiative. If you can't point to a specific plan reference, the deal is opportunistic.", acceptanceParams: [{ label: "Plan Section Reference", defaultValue: "Specific page/section of strategic plan", type: "text" }] },
        { name: "Build-vs-Buy Justification", weight: 25, rubric: [{ score: 10, label: "Acquisition is clearly faster, cheaper, and lower-risk than organic build with documented analysis" }, { score: 7, label: "Acquisition preferred over build on 2 of 3 criteria (speed, cost, risk)" }, { score: 5, label: "Build vs. buy is roughly equivalent; acquisition justified by speed alone" }, { score: 3, label: "Organic build is feasible and may be cheaper; acquisition premium not justified" }, { score: 0, label: "Organic build is clearly preferable — acquisition destroys value vs. internal development" }], testGuidance: "Corporate acquirers face unique scrutiny on build vs. buy. The board will ask: why can't we build this ourselves? Prepare a rigorous comparison covering: timeline, total cost, capability gap closure speed, competitive response window, and execution risk.", acceptanceParams: [{ label: "Build Cost Estimate", defaultValue: "Internal organic build cost analysis", type: "text" }] },
        { name: "Competitive Threat Assessment", weight: 25, rubric: [{ score: 10, label: "Acquisition blocks a specific competitor from acquiring the same target — documented competitive intelligence" }, { score: 7, label: "Deal strengthens competitive position and creates meaningful barriers" }, { score: 5, label: "Moderately improves competitive standing; competitor could find alternatives" }, { score: 3, label: "Minimal competitive impact — deal doesn't change competitive dynamics" }, { score: 0, label: "No competitive benefit; competitor landscape unchanged" }], testGuidance: "Assess: which competitors would benefit from acquiring this target? What would happen if a top-3 competitor acquired it instead? Competitive denial value is real but must be quantified, not assumed.", acceptanceParams: [{ label: "Competitive Threat", defaultValue: "Identify 2-3 competitors who would benefit from this target", type: "text" }] },
        { name: "Capability Gap Closure", weight: 20, rubric: [{ score: 10, label: "Fills a critical capability gap that is documented in the strategic plan as blocking growth" }, { score: 7, label: "Adds meaningful capability that accelerates strategic roadmap by 12+ months" }, { score: 5, label: "Adds complementary capability — nice to have but not blocking" }, { score: 3, label: "Minimal incremental capability — overlaps with existing corporate assets" }, { score: 0, label: "No capability addition; duplicate of existing corporate capabilities" }], testGuidance: "Map against the corporate capability matrix. Which cells does this fill? How critical are those cells to the strategic plan? If the plan can proceed without this capability, score lower.", acceptanceParams: [{ label: "Capability Gap", defaultValue: "Named capability gap from strategic plan", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "strategic-fit-memo", label: "Strategic Fit Memo" }, { id: "build-vs-buy", label: "Build vs. Buy Analysis" }, { id: "competitive-intel", label: "Competitive Intelligence Brief" }],
    },
    {
      code: "G2", name: "Market & Competitive Position", purpose: "Evaluate the target's market position with emphasis on customer overlap and strategic value to the corporate acquirer.", type: "scored", minimumScore: 55, declineThreshold: 40,
      rule: "Weighted composite ≥55 to advance.",
      dimensions: [
        { name: "Market Growth Rate", weight: 25, rubric: [{ score: 10, label: ">10% market CAGR with structural tailwinds" }, { score: 7, label: "5-10% CAGR with clear growth drivers" }, { score: 5, label: "GDP-level growth (2-5%)" }, { score: 3, label: "Flat to declining" }, { score: 0, label: "Secular decline" }], testGuidance: "Source market growth from industry reports. Corporate acquirers prefer stable, growing markets over high-risk hypergrowth.", acceptanceParams: [{ label: "Min Market CAGR", defaultValue: ">3%", type: "text" }] },
        { name: "Target Market Position", weight: 25, rubric: [{ score: 10, label: "Market leader or top-3 with defensible advantages" }, { score: 7, label: "Strong position with loyal customer base" }, { score: 5, label: "Mid-tier — competitive but not differentiated" }, { score: 3, label: "Commodity player" }, { score: 0, label: "Declining share" }], testGuidance: "Assess market share, customer retention, pricing power, brand recognition.", acceptanceParams: [{ label: "Market Position", defaultValue: "Top-5 in served market", type: "text" }] },
        { name: "Customer Overlap Value", weight: 30, rubric: [{ score: 10, label: ">50% of target's customers are existing corporate customers — immediate wallet share expansion" }, { score: 7, label: "30-50% overlap with clear cross-sell rationale" }, { score: 5, label: "15-30% overlap" }, { score: 3, label: "<15% overlap" }, { score: 0, label: "No overlap — completely new customer base" }], testGuidance: "Customer overlap is the strongest indicator of post-acquisition synergy for corporate acquirers. Higher overlap = faster revenue realization. Map target customer list against corporate CRM.", acceptanceParams: [{ label: "Customer Overlap", defaultValue: ">20% of top 100 accounts", type: "text" }] },
        { name: "Disruption Risk", weight: 20, rubric: [{ score: 10, label: "Minimal disruption risk; target operates in stable, regulated market" }, { score: 7, label: "Low disruption risk; technology shifts are gradual and predictable" }, { score: 5, label: "Moderate disruption risk; technology shift possible in 5-7 year horizon" }, { score: 3, label: "High disruption risk; adjacent technology could displace in 3-5 years" }, { score: 0, label: "Target's market is actively being disrupted; >30% technology displacement risk" }], testGuidance: "Corporate acquirers typically hold assets 7-10+ years. Assess technology disruption, regulatory change, and market structure risk over that horizon.", acceptanceParams: [{ label: "Disruption Horizon", defaultValue: ">7 years before material disruption risk", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "market-assessment", label: "Market Assessment Brief" }, { id: "customer-overlap", label: "Customer Overlap Analysis" }],
    },
    {
      code: "G3", name: "Business Model & Organizational Compatibility", purpose: "Assess business model fit and organizational integration complexity.", type: "scored", minimumScore: 55, declineThreshold: 40,
      rule: "Weighted composite ≥55 to advance.",
      dimensions: [
        { name: "Revenue Model Compatibility", weight: 30, rubric: [{ score: 10, label: "Identical revenue model with direct pricing overlay" }, { score: 7, label: "Compatible with minor differences" }, { score: 5, label: "Different but reconcilable within 12 months" }, { score: 3, label: "Conflicting models requiring restructuring" }, { score: 0, label: "Fundamentally incompatible" }], testGuidance: "Compare contract structures, pricing models, billing cycles. Corporate acquirers need model compatibility for consolidated reporting.", acceptanceParams: [{ label: "Model Compatibility", defaultValue: ">60% revenue model overlap", type: "text" }] },
        { name: "GTM Motion Alignment", weight: 20, rubric: [{ score: 10, label: "Same sales motion, buyer persona, and deal cycle" }, { score: 7, label: "Similar GTM with minor channel differences" }, { score: 5, label: "Different GTM but shared buyer personas" }, { score: 3, label: "Different GTM and different buyers" }, { score: 0, label: "Conflicting GTM that would confuse shared customers" }], testGuidance: "Assess sales motion (enterprise vs. mid-market vs. SMB), channel strategy (direct vs. partner), and buyer personas. Misaligned GTM is a common source of post-acquisition revenue attrition.", acceptanceParams: [] },
        { name: "Organizational Integration", weight: 30, rubric: [{ score: 10, label: "Target's org structure maps cleanly to corporate divisions with clear reporting lines" }, { score: 7, label: "Integration path is clear with defined org structure changes" }, { score: 5, label: "Organizational restructuring required but manageable" }, { score: 3, label: "Significant org restructuring; role redundancies create conflict" }, { score: 0, label: "Cannot integrate into corporate structure without destroying target's operational effectiveness" }], testGuidance: "Map target's org chart to the corporate structure. Where does it report? Which functions are absorbed vs. retained? How many roles are redundant? Corporate acquisitions often fail when integration destroys the target's operational culture.", acceptanceParams: [{ label: "Integration Model", defaultValue: "Standalone unit, absorbed division, or hybrid", type: "text" }] },
        { name: "Cost Structure Compatibility", weight: 20, rubric: [{ score: 10, label: "Target operates at similar margins; overhead can be consolidated" }, { score: 7, label: "Margin differences manageable; clear cost synergies" }, { score: 5, label: "Different cost structures but reconcilable" }, { score: 3, label: "Target has higher cost structure; margin compression risk" }, { score: 0, label: "Cost dissynergies — target would increase corporate cost base" }], testGuidance: "Compare cost structures including compensation, benefits, facilities, technology. Corporate acquirers often have higher comp structures — assess the cost of harmonization.", acceptanceParams: [] },
      ],
      evidenceArtifacts: [{ id: "org-assessment", label: "Organizational Integration Assessment" }, { id: "bmc-comparison", label: "Business Model Comparison" }],
    },
    {
      code: "G4", name: "Financial Profile & Valuation", purpose: "Financial analysis with emphasis on strategic premium justification. Corporate acquirers often pay above PE multiples — the premium must be justified.", type: "scored", minimumScore: 55, declineThreshold: 35,
      rule: "Weighted composite ≥55 to advance.",
      dimensions: [
        { name: "Revenue Quality", weight: 20, rubric: [{ score: 10, label: ">85% contracted/recurring; <5% concentration; strong growth" }, { score: 7, label: "60-85% contracted; moderate concentration; stable growth" }, { score: 5, label: "40-60% contracted; some concentration" }, { score: 3, label: "<40% contracted; high concentration" }, { score: 0, label: "Mostly spot; declining; high concentration" }], testGuidance: "Standard revenue quality assessment. Corporate acquirers value predictability above growth.", acceptanceParams: [{ label: "Min Contracted %", defaultValue: ">50%", type: "text" }] },
        { name: "Margin Profile", weight: 20, rubric: [{ score: 10, label: ">25% EBITDA margin with expansion trend" }, { score: 7, label: "18-25% stable margins" }, { score: 5, label: "12-18% margins" }, { score: 3, label: "8-12% margins" }, { score: 0, label: "<8% or operating losses" }], testGuidance: "Normalize EBITDA. Compare to corporate segment margins.", acceptanceParams: [{ label: "Min EBITDA Margin", defaultValue: ">12%", type: "text" }] },
        { name: "Strategic Premium Justification", weight: 30, rubric: [{ score: 10, label: "Premium fully justified by quantified strategic value (market access, capability, competitive denial) exceeding premium paid" }, { score: 7, label: "Premium largely justified — strategic value is material and quantifiable" }, { score: 5, label: "Premium partially justified — some strategic value but difficult to quantify" }, { score: 3, label: "Premium weakly justified — mostly qualitative rationale" }, { score: 0, label: "Premium not justified — financial returns alone cannot support the price" }], testGuidance: "Corporate acquirers typically pay 1-3x turns above PE multiples. This premium must be justified by quantified strategic value: market access, customer relationships, technology, competitive positioning, or regulatory advantage. The strategic premium should be documented in dollars, not just narrative.", acceptanceParams: [{ label: "Strategic Premium", defaultValue: "Quantify the strategic value in $ terms", type: "text" }, { label: "Premium Justification", defaultValue: "Board-ready justification document", type: "text" }] },
        { name: "Valuation Attractiveness", weight: 20, rubric: [{ score: 10, label: "Below market comps even with strategic premium" }, { score: 7, label: "At market comps — premium justified by strategic value" }, { score: 5, label: "1-2x turns above comps — requires strong strategic rationale" }, { score: 3, label: ">2x turns above comps — premium stretches justification" }, { score: 0, label: "Materially above any reasonable valuation framework" }], testGuidance: "Compare to precedent transactions (strategic and financial acquirers separately). Assess whether the proposed price including strategic premium is defensible to the board.", acceptanceParams: [{ label: "Valuation Range", defaultValue: "Comparable transaction range", type: "text" }] },
        { name: "Growth Profile", weight: 10, rubric: [{ score: 10, label: ">15% revenue CAGR with organic drivers" }, { score: 7, label: "8-15% growth" }, { score: 5, label: "3-8% growth" }, { score: 3, label: "Flat" }, { score: 0, label: "Declining" }], testGuidance: "Growth trajectory over 3-5 years. Corporate acquirers prefer steady growers over high-growth/high-risk profiles.", acceptanceParams: [] },
      ],
      evidenceArtifacts: [{ id: "financial-summary", label: "Financial Summary" }, { id: "strategic-premium", label: "Strategic Premium Justification" }, { id: "valuation-comps", label: "Valuation Comparables" }],
    },
    {
      code: "G5", name: "Organizational & Integration Planning", purpose: "Deep assessment of organizational fit, cultural compatibility, and integration complexity. Corporate integrations are the most complex of any acquirer type.", type: "scored", minimumScore: 70, declineThreshold: 50,
      rule: "Weighted composite ≥70 to advance. Highest integration bar of any template.",
      dimensions: [
        { name: "Cultural Integration Assessment", weight: 30, rubric: [{ score: 10, label: "Strong cultural alignment; shared values, decision-making style, and customer orientation" }, { score: 7, label: "Compatible cultures; normal integration friction expected and manageable" }, { score: 5, label: "Cultural differences present; requires active change management program" }, { score: 3, label: "Significant cultural friction; high risk of talent attrition and morale decline" }, { score: 0, label: "Fundamentally incompatible cultures; integration would destroy target's effectiveness" }], testGuidance: "Cultural fit is the #1 predictor of corporate acquisition success. Assess through management interactions, site visits, employee surveys (if available), Glassdoor reviews, and industry reputation. Key factors: decision-making speed, risk tolerance, formality level, innovation culture.", acceptanceParams: [{ label: "Cultural Assessment", defaultValue: "Management site visits + employee pulse (if accessible)", type: "text" }] },
        { name: "Organizational Design", weight: 20, rubric: [{ score: 10, label: "Clear org design with defined reporting lines, retained leadership, and managed redundancies" }, { score: 7, label: "Org design drafted; key role decisions made; some redundancies to be resolved" }, { score: 5, label: "High-level org concept; detailed role mapping not yet complete" }, { score: 3, label: "Org design unclear; significant role overlap with no resolution plan" }, { score: 0, label: "No org design work done; integration will be ad hoc" }], testGuidance: "Map every senior role in the target to the post-acquisition org chart. Identify retained roles, eliminated roles, and new roles. Every eliminated role is a cost saving AND a retention risk. Handle with care.", acceptanceParams: [{ label: "Org Design", defaultValue: "Detailed post-acquisition org chart", type: "text" }] },
        { name: "Systems Compatibility", weight: 25, rubric: [{ score: 10, label: "Target runs compatible enterprise systems; integration path is proven" }, { score: 7, label: "Different systems but migration path is clear with corporate IT resources" }, { score: 5, label: "Significant systems migration; 12-18 month timeline" }, { score: 3, label: "Legacy systems with complex data migration requirements" }, { score: 0, label: "Systems are incompatible; parallel operations required indefinitely" }], testGuidance: "Corporate IT integration is often the most expensive and slowest workstream. Map ERP, CRM, HRIS, financial reporting, security/compliance systems. Assess whether corporate IT has capacity for another integration.", acceptanceParams: [{ label: "IT Assessment", defaultValue: "Systems compatibility matrix", type: "text" }] },
        { name: "Change Management Readiness", weight: 25, rubric: [{ score: 10, label: "Dedicated change management team with proven corporate integration methodology" }, { score: 7, label: "Change management plan drafted; communications strategy in place" }, { score: 5, label: "Change management acknowledged but no dedicated resources" }, { score: 3, label: "No change management planning; corporate assumes target will simply adapt" }, { score: 0, label: "Active resistance expected; no plan to manage transition" }], testGuidance: "Corporate acquisitions affect hundreds of people. Assess: is there a communications plan for Day 1? Are retention packages prepared for key talent? Is there a dedicated integration leader? Has the corporate HR team been briefed?", acceptanceParams: [{ label: "Change Plan", defaultValue: "Day-1 communications + 90-day integration plan", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "cultural-assessment", label: "Cultural Assessment" }, { id: "org-design", label: "Post-Acquisition Org Design" }, { id: "integration-plan", label: "Integration Master Plan" }],
    },
    {
      code: "G6", name: "Risk Assessment", purpose: "Comprehensive risk assessment with elevated weight on regulatory, antitrust, and public company disclosure risks.", type: "scored", minimumScore: 60, declineThreshold: 40,
      rule: "Weighted composite ≥60. Regulatory risks can kill corporate deals regardless of strategic value.",
      dimensions: [
        { name: "Regulatory Approval Risk", weight: 25, rubric: [{ score: 10, label: "No regulatory filings required; standard M&A process" }, { score: 7, label: "HSR filing required but approval expected within 30 days; no material concerns" }, { score: 5, label: "Regulatory review expected; 3-6 month timeline but no fatal flags" }, { score: 3, label: "Material regulatory risk; second request possible; 6-12 month delay risk" }, { score: 0, label: "Regulatory block likely; antitrust or foreign investment concerns are material" }], testGuidance: "Assess all regulatory filing requirements: HSR Act, CFIUS, sector-specific regulators. Engage antitrust counsel early. For public acquirers, assess SEC disclosure requirements and market timing implications.", acceptanceParams: [{ label: "HSR Filing", defaultValue: "Required / Not Required", type: "text" }, { label: "CFIUS Risk", defaultValue: "Low / Moderate / High", type: "text" }] },
        { name: "Antitrust / Market Concentration", weight: 20, rubric: [{ score: 10, label: "Combined entity has <15% market share; no horizontal overlap concerns" }, { score: 7, label: "15-25% combined share; defensible as pro-competitive" }, { score: 5, label: "25-35% combined share; requires competitive effects analysis" }, { score: 3, label: "35-50% combined share; material antitrust risk" }, { score: 0, label: ">50% combined share; likely to face antitrust challenge" }], testGuidance: "Calculate combined market share in all overlapping product/service markets. Use the DOJ/FTC HHI framework. Engage antitrust counsel if combined share exceeds 25% in any market. Document efficiencies and pro-competitive effects.", acceptanceParams: [{ label: "Combined Market Share", defaultValue: "<25% in any defined market", type: "text" }] },
        { name: "Key Person Risk", weight: 20, rubric: [{ score: 10, label: "Distributed leadership; no single person critical" }, { score: 7, label: "Key leaders identified; retention packages prepared" }, { score: 5, label: "Founder-dependent for some relationships" }, { score: 3, label: "Critical dependency on 1-2 people" }, { score: 0, label: "Single person IS the business" }], testGuidance: "Standard key person assessment. Corporate acquirers should plan for higher management turnover — target executives often leave within 18 months of corporate acquisition.", acceptanceParams: [{ label: "Key Person Dependency", defaultValue: "<25% revenue tied to any single person", type: "text" }] },
        { name: "Legal & Compliance", weight: 20, rubric: [{ score: 10, label: "Clean legal profile; full compliance; all permits transferable" }, { score: 7, label: "Minor legal matters; standard compliance" }, { score: 5, label: "Some legal complexity requiring outside counsel" }, { score: 3, label: "Material litigation or compliance gaps" }, { score: 0, label: "Fatal legal flag" }], testGuidance: "Review: pending litigation, regulatory compliance history, environmental liabilities, IP ownership, data privacy compliance, export controls. Corporate acquirers face higher standards — target must meet corporate compliance framework.", acceptanceParams: [{ label: "Legal Diligence", defaultValue: "No material unresolved issues", type: "text" }] },
        { name: "Public Relations / Communications", weight: 15, rubric: [{ score: 10, label: "Deal announcement will be well-received by all stakeholders" }, { score: 7, label: "Positive reception expected with minor stakeholder management needed" }, { score: 5, label: "Mixed reception; requires proactive communications strategy" }, { score: 3, label: "Negative reception likely from employees, customers, or investors" }, { score: 0, label: "Deal would trigger material negative reaction from key stakeholders" }], testGuidance: "For public acquirers: assess investor, analyst, customer, and employee reaction. Prepare communications for each audience. For any acquirer: assess community impact, supplier reaction, and media coverage risk.", acceptanceParams: [{ label: "Communications Plan", defaultValue: "Stakeholder-specific communications prepared", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "regulatory-analysis", label: "Regulatory & Antitrust Analysis" }, { id: "risk-register", label: "Risk Register" }, { id: "legal-summary", label: "Legal Diligence Summary" }],
    },
    {
      code: "G7", name: "Board Recommendation", purpose: "Synthesize all gate outputs into a board-ready recommendation. For corporate acquirers, the board is the ultimate decision-maker.", type: "decision", minimumScore: null, declineThreshold: null,
      rule: "Composite ≥65 = RECOMMEND APPROVAL; 50-64 = CONDITIONAL (specify conditions); <50 = DO NOT RECOMMEND. Board requires dual authorization from Corp Dev and sponsoring business unit.",
      dimensions: [
        { name: "Strategic Attractiveness", weight: 35, rubric: [{ score: 10, label: "Transformative acquisition — redefines corporate competitive position" }, { score: 7, label: "Strong strategic addition that clearly advances board strategy" }, { score: 5, label: "Acceptable strategic fit" }, { score: 3, label: "Marginal strategic value" }, { score: 0, label: "No strategic alignment" }], testGuidance: "Synthesize G1 strategic alignment into a board-ready strategic narrative. This dimension carries the highest weight because strategic justification is the corporate acquirer's primary mandate.", acceptanceParams: [] },
        { name: "Financial Attractiveness", weight: 20, rubric: [{ score: 10, label: "Accretive in year 1; returns above WACC with conservative assumptions" }, { score: 7, label: "Accretive within 2 years; reasonable return profile" }, { score: 5, label: "Breakeven within 3 years" }, { score: 3, label: "Dilutive for 3+ years; requires strategic premium justification" }, { score: 0, label: "Value destructive" }], testGuidance: "Synthesize G4 financials. EPS accretion/dilution analysis for public companies. ROIC vs. WACC for all corporate acquirers.", acceptanceParams: [] },
        { name: "Integration Feasibility", weight: 25, rubric: [{ score: 10, label: "Integration plan is comprehensive; team has capacity; cultural fit is strong" }, { score: 7, label: "Integration plan solid; manageable risks" }, { score: 5, label: "Integration doable but stretches resources" }, { score: 3, label: "Material integration risks" }, { score: 0, label: "Cannot integrate without significant disruption" }], testGuidance: "Synthesize G5 organizational integration. For the board: what will the first year look like? How much management attention does this require?", acceptanceParams: [] },
        { name: "Risk-Adjusted Recommendation", weight: 20, rubric: [{ score: 10, label: "All risks identified, quantified, and mitigated; high confidence in execution" }, { score: 7, label: "Risks managed with reasonable mitigation plans" }, { score: 5, label: "Some residual risks; monitoring required" }, { score: 3, label: "Material unmitigated risks" }, { score: 0, label: "Unacceptable risk profile" }], testGuidance: "Synthesize G6 risk assessment. Present the top 5 risks with probability, impact, and mitigation status. Board members need a clear risk/reward framework.", acceptanceParams: [] },
      ],
      evidenceArtifacts: [{ id: "board-memo", label: "Board Recommendation Memo" }, { id: "composite-scorecard", label: "Composite Scorecard (G0-G7)" }, { id: "financial-model", label: "Board Financial Model" }],
    },
  ],
};
