// ═══════════════════════════════════════════════════════════════
// AMP v2 — Family Office / HoldCo Template
//
// Ultra-conservative, long-term hold (10-20+ years or perpetual).
// Cash flow durability, management continuity, downside protection.
// No exit modeling — focus on permanent capital allocation.
// ═══════════════════════════════════════════════════════════════

export const FAMILY_OFFICE_TEMPLATE = {
  name: "Family Office / HoldCo",
  slug: "family-office",
  archetype: "family_office",
  description: "Methodology for family offices and permanent holding companies evaluating long-term or perpetual acquisitions. Prioritizes cash flow durability, management self-sufficiency, and downside protection over growth or exit-driven returns.",
  version: "1.0.0",
  isPublished: true,
  isDefault: false,
  authoredBy: "Alio Foundry",
  changeLog: [{ version: "1.0.0", date: "2026-04-03", changes: ["Initial release"] }],

  personaSchema: {
    fields: [
      { key: "holdingPeriod", label: "Expected Hold Period", required: true },
      { key: "riskTolerance", label: "Risk Tolerance", required: true },
      { key: "dividendExpectation", label: "Dividend / Cash Distribution Needs", required: true },
      { key: "managementExpectation", label: "Management Continuity Expectation", required: true },
      { key: "governanceStructure", label: "Governance Structure", required: true },
    ],
  },

  weightPropagationRules: [
    { condition: "holdingPeriod === 'Perpetual'", gateCode: "G6", dimensionName: "Key Person Risk", adjustment: 10, reason: "Perpetual hold elevates succession planning importance" },
    { condition: "holdingPeriod === 'Perpetual'", gateCode: "G4", dimensionName: "Cash Flow Durability", adjustment: 10, reason: "Perpetual hold requires maximum cash flow stability" },
    { condition: "dividendExpectation === 'High (30%+)'", gateCode: "G4", dimensionName: "Cash Yield at Purchase Price", adjustment: 15, reason: "High distribution needs require stronger entry yield" },
    { condition: "managementExpectation === 'Founder must stay'", gateCode: "G6", dimensionName: "Key Person Risk", adjustment: 20, reason: "Founder dependency must be thoroughly assessed" },
  ],

  gatesConfig: [
    {
      code: "G0", name: "Universe Qualification", purpose: "Conservative hard filter: cash flow minimum, cyclicality screen, and sector/value alignment.", type: "binary", minimumScore: null, declineThreshold: null,
      rule: "ALL dimensions must pass. Family office filters are the tightest of any template.",
      dimensions: [
        { name: "Sector Fit", weight: 20, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Target must operate in a sector aligned with the family's values and investment philosophy. Some family offices have explicit exclusion lists (tobacco, gambling, weapons). Verify alignment.", acceptanceParams: [{ label: "Sector", defaultValue: "Aligned with family investment charter", type: "text" }] },
        { name: "Size Parameters", weight: 20, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Revenue and EBITDA must fall within the family office's acquisition band. Family offices typically target $5M-$100M revenue businesses that are large enough to be self-managing but small enough for the family to oversee.", acceptanceParams: [{ label: "Revenue Range", defaultValue: "$5M–$100M", type: "text" }, { label: "EBITDA Minimum", defaultValue: "$2M+", type: "text" }] },
        { name: "Cash Flow Minimum Threshold", weight: 30, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Target must demonstrate consistent positive free cash flow for 3+ consecutive years. Businesses that require significant ongoing capital investment to maintain operations are less suitable for long-term passive hold.", acceptanceParams: [{ label: "Min FCF", defaultValue: "3 consecutive years of positive FCF", type: "text" }, { label: "EBITDA Margin", defaultValue: ">15% normalized", type: "text" }] },
        { name: "Industry Cyclicality Screen", weight: 30, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Assess the target's industry cyclicality over a full economic cycle (7-10 years). Revenue volatility >25% peak-to-trough is a red flag for long-term holders. Prefer industries with non-discretionary demand, recurring revenue models, and low correlation to GDP cycles.", acceptanceParams: [{ label: "Revenue Volatility", defaultValue: "<25% peak-to-trough over full cycle", type: "text" }, { label: "Cyclicality Rating", defaultValue: "Non-cyclical or mildly cyclical", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "qualification-card", label: "Family Office Qualification Scorecard" }, { id: "cyclicality-analysis", label: "Industry Cyclicality Analysis" }],
    },
    {
      code: "G1", name: "Portfolio Fit & Cash Flow Thesis", purpose: "Assess how this acquisition fits the family's portfolio philosophy. Focus on cash flow contribution, diversification, and management self-sufficiency.", type: "scored", minimumScore: 60, declineThreshold: 40,
      rule: "Weighted composite ≥60 to advance.",
      dimensions: [
        { name: "Cash Flow Contribution", weight: 30, rubric: [{ score: 10, label: "Immediately cash-generative; will fund distributions from year 1 with 20%+ free cash yield" }, { score: 7, label: "Strong cash generation; 15-20% free cash yield; predictable distributions" }, { score: 5, label: "Moderate cash generation; 10-15% yield; some reinvestment required" }, { score: 3, label: "Low cash yield (<10%); most earnings must be reinvested" }, { score: 0, label: "Cash-consuming; requires capital injection to operate" }], testGuidance: "Calculate free cash flow yield at the proposed purchase price. Family offices acquiring for perpetual hold need businesses that generate cash, not consume it. Deduct maintenance capex, working capital needs, and minimum reinvestment to sustain operations.", acceptanceParams: [{ label: "Target Cash Yield", defaultValue: ">15% FCF yield at purchase price", type: "text" }] },
        { name: "Diversification Benefit", weight: 25, rubric: [{ score: 10, label: "Adds uncorrelated revenue stream; reduces portfolio concentration meaningfully" }, { score: 7, label: "Good diversification — different sector, geography, or customer base from existing holdings" }, { score: 5, label: "Moderate diversification; some overlap with existing portfolio" }, { score: 3, label: "High correlation with existing holdings; limited diversification" }, { score: 0, label: "Increases portfolio concentration in an already-overweight sector" }], testGuidance: "Map against the family's existing portfolio. Does this acquisition reduce concentration risk or increase it? Assess correlation to other holdings across: sector, geography, customer type, economic cycle sensitivity, and revenue model.", acceptanceParams: [{ label: "Portfolio Overlap", defaultValue: "<30% revenue correlation with existing holdings", type: "text" }] },
        { name: "Management Self-Sufficiency", weight: 25, rubric: [{ score: 10, label: "Proven management team operates independently; family oversight is strategic only" }, { score: 7, label: "Strong management; needs minimal family involvement for daily operations" }, { score: 5, label: "Adequate management but may need a hire or two to fill gaps" }, { score: 3, label: "Management is thin; family would need to be involved operationally" }, { score: 0, label: "No capable management; family would need to recruit and install a team" }], testGuidance: "Family offices typically don't operate businesses — they oversee them. Assess the management team's ability to run the business independently: depth of bench, track record, succession planning, and comfort operating without founder oversight.", acceptanceParams: [{ label: "Management Assessment", defaultValue: "Can operate independently for 12+ months", type: "text" }] },
        { name: "Value Alignment", weight: 20, rubric: [{ score: 10, label: "Perfect alignment with family values, ESG standards, and community impact philosophy" }, { score: 7, label: "Strong alignment; minor differences manageable" }, { score: 5, label: "Neutral — no conflicts but no special alignment" }, { score: 3, label: "Some value tension; business practices may conflict with family standards" }, { score: 0, label: "Material value conflict — business would embarrass the family" }], testGuidance: "Family offices invest the family's reputation alongside capital. Assess: environmental practices, labor practices, community impact, product safety, and public perception. A profitable business that damages the family's reputation is not a good investment.", acceptanceParams: [{ label: "Values Check", defaultValue: "No conflicts with family investment charter", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "portfolio-fit", label: "Portfolio Fit Analysis" }, { id: "cash-flow-model", label: "Cash Flow Contribution Model" }],
    },
    {
      code: "G2", name: "Market & Competitive Position", purpose: "Assess market stability and durability for long-term hold. Penalize disruption risk; reward non-discretionary demand.", type: "scored", minimumScore: 65, declineThreshold: 45,
      rule: "Weighted composite ≥65. Higher bar than PE — long hold requires durable market position.",
      dimensions: [
        { name: "Market Growth Rate", weight: 25, rubric: [{ score: 10, label: "Stable 3-7% growth with non-discretionary demand drivers" }, { score: 7, label: "GDP-level growth (2-5%) with stability" }, { score: 5, label: "Flat but stable market" }, { score: 3, label: "Declining market without clear stabilization" }, { score: 0, label: "Secular decline with disruption risk" }], testGuidance: "Family offices prefer stable, predictable markets over high-growth/high-risk. A 3% CAGR in a non-cyclical market is more attractive than 15% growth in a volatile sector. Focus on demand durability over growth rate.", acceptanceParams: [{ label: "Market Stability", defaultValue: "Non-cyclical or mildly cyclical", type: "text" }] },
        { name: "Target Market Position", weight: 25, rubric: [{ score: 10, label: "Local/regional market leader with high switching costs and customer loyalty" }, { score: 7, label: "Strong niche position with defensible competitive advantages" }, { score: 5, label: "Mid-tier position — competitive but vulnerable to disruption" }, { score: 3, label: "Commodity position with low barriers to entry" }, { score: 0, label: "Declining position with no path to differentiation" }], testGuidance: "Long-term hold requires durable competitive position. Prioritize: regulatory moats, switching costs, local market dominance, customer relationships, and brand loyalty. These persist over 10-20 year horizons.", acceptanceParams: [{ label: "Competitive Moat", defaultValue: "At least one durable competitive advantage", type: "text" }] },
        { name: "Disruption Risk", weight: 30, rubric: [{ score: 10, label: "Industry highly resistant to technology disruption; physical/local service requirements create barriers" }, { score: 7, label: "Low disruption risk; technology changes are gradual and adoptable" }, { score: 5, label: "Moderate disruption risk; must invest in technology to maintain position" }, { score: 3, label: "Significant disruption risk within 10-year hold horizon" }, { score: 0, label: "Active disruption underway; >30% of revenue model at risk" }], testGuidance: "This is the most important dimension for family offices. Over a 10-20 year horizon, almost every industry faces some disruption. Score based on the probability and timeline of material disruption to the target's core revenue model.", acceptanceParams: [{ label: "Disruption Horizon", defaultValue: ">10 years before material disruption risk", type: "text" }] },
        { name: "Customer Retention", weight: 20, rubric: [{ score: 10, label: ">95% annual customer retention with multi-year contracts" }, { score: 7, label: "90-95% retention with strong relationships" }, { score: 5, label: "85-90% retention — acceptable but watch trends" }, { score: 3, label: "80-85% retention — below average; churn risk" }, { score: 0, label: "<80% retention — high churn business" }], testGuidance: "Customer retention is the best proxy for long-term revenue durability. Calculate gross and net retention rates. Analyze churn reasons. High-retention businesses are the foundation of perpetual hold strategies.", acceptanceParams: [{ label: "Min Retention", defaultValue: ">90% annual customer retention", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "market-assessment", label: "Market Durability Assessment" }, { id: "disruption-analysis", label: "Technology Disruption Analysis" }],
    },
    {
      code: "G3", name: "Business Model Compatibility", purpose: "Ensure the business can operate independently within the family portfolio.", type: "scored", minimumScore: 55, declineThreshold: 40,
      rule: "Weighted composite ≥55 to advance.",
      dimensions: [
        { name: "Revenue Model Durability", weight: 30, rubric: [{ score: 10, label: ">80% contracted/recurring revenue with multi-year terms" }, { score: 7, label: "60-80% contracted; strong rebooking rates" }, { score: 5, label: "40-60% contracted with some spot exposure" }, { score: 3, label: "<40% contracted; high spot/project dependency" }, { score: 0, label: "Mostly project/spot revenue with no predictability" }], testGuidance: "Revenue model durability is critical for long-term hold. Contracted and recurring revenue is vastly preferred over project-based or spot revenue. Multi-year contracts with escalators provide the most predictable cash flow.", acceptanceParams: [{ label: "Contract Coverage", defaultValue: ">60% of revenue under contract", type: "text" }] },
        { name: "Operational Independence", weight: 30, rubric: [{ score: 10, label: "Fully self-contained operations; no dependency on family portfolio resources" }, { score: 7, label: "Largely independent; may share 1-2 back-office functions with portfolio" }, { score: 5, label: "Some operational dependencies; needs access to shared services" }, { score: 3, label: "Significant operational dependencies; would struggle standalone" }, { score: 0, label: "Cannot operate independently without portfolio support infrastructure" }], testGuidance: "Family offices want businesses that run themselves. Can this business operate profitably without any shared services, management attention, or capital beyond what it generates internally?", acceptanceParams: [{ label: "Independence", defaultValue: "Can operate 12+ months without owner involvement", type: "text" }] },
        { name: "Capital Intensity", weight: 20, rubric: [{ score: 10, label: "Asset-light; maintenance capex <5% of revenue; minimal working capital needs" }, { score: 7, label: "Moderate capital needs; 5-10% capex; predictable working capital" }, { score: 5, label: "Capital-intensive but manageable; 10-15% capex" }, { score: 3, label: "Heavy capital needs; >15% capex; unpredictable investment cycles" }, { score: 0, label: "Extremely capital-intensive; cash flow consumed by reinvestment requirements" }], testGuidance: "Family offices want cash-generative businesses, not cash-consuming ones. Calculate maintenance capex as % of revenue. Assess working capital seasonality. The less capital the business needs to maintain operations, the higher the distributable cash flow.", acceptanceParams: [{ label: "Capex Ratio", defaultValue: "<10% of revenue in maintenance capex", type: "text" }] },
        { name: "Customer Segment Stability", weight: 20, rubric: [{ score: 10, label: "Diversified customer base with non-discretionary demand" }, { score: 7, label: "Stable customer base with moderate concentration" }, { score: 5, label: "Some concentration; manageable with retention strategy" }, { score: 3, label: "High concentration or discretionary demand" }, { score: 0, label: "Customer base is volatile or highly concentrated" }], testGuidance: "Assess customer stability over full economic cycles. Non-discretionary services to essential industries provide the most stable revenue base for long-term hold.", acceptanceParams: [{ label: "Concentration", defaultValue: "No customer >15% of revenue", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "business-model", label: "Business Model Durability Assessment" }, { id: "independence-check", label: "Operational Independence Checklist" }],
    },
    {
      code: "G4", name: "Financial Profile & Cash Yield", purpose: "Conservative financial analysis focused on cash flow durability, entry yield, and downside protection. No exit modeling.", type: "scored", minimumScore: 60, declineThreshold: 40,
      rule: "Weighted composite ≥60. Higher margin and cash flow thresholds than PE templates.",
      dimensions: [
        { name: "Cash Flow Durability", weight: 30, rubric: [{ score: 10, label: "10+ years of consistent FCF; minimal year-over-year variance; no negative FCF years" }, { score: 7, label: "7+ years positive FCF with <15% annual variance" }, { score: 5, label: "5+ years mostly positive FCF with some variance" }, { score: 3, label: "Inconsistent FCF; 1-2 negative years in recent history" }, { score: 0, label: "Unpredictable or declining FCF; negative trend" }], testGuidance: "Analyze free cash flow over the longest available history. Normalize for one-time items. Calculate year-over-year variance. Family offices need cash flow predictability above all else — a business that throws off $2M every year is more valuable than one that alternates between $4M and -$1M.", acceptanceParams: [{ label: "FCF History", defaultValue: "5+ consecutive years of positive FCF", type: "text" }, { label: "FCF Variance", defaultValue: "<20% year-over-year variance", type: "text" }] },
        { name: "Cash Yield at Purchase Price", weight: 35, rubric: [{ score: 10, label: ">20% unlevered FCF yield at purchase price — exceptional entry point" }, { score: 7, label: "15-20% FCF yield — strong cash-on-cash return from day 1" }, { score: 5, label: "10-15% FCF yield — acceptable if growth supports future yield expansion" }, { score: 3, label: "7-10% FCF yield — thin margin for distribution and reinvestment" }, { score: 0, label: "<7% FCF yield — overpaying for the cash flow stream" }], testGuidance: "Calculate unlevered free cash flow yield: (normalized FCF) / (proposed purchase price). This is the family office's primary return metric — there's no exit event, so the entry yield determines long-term returns. Compare to the family's cost of capital and alternative investment yields.", acceptanceParams: [{ label: "Target FCF Yield", defaultValue: ">15% at entry", type: "text" }, { label: "Purchase Price", defaultValue: "4-6x normalized EBITDA", type: "text" }] },
        { name: "Margin Profile", weight: 20, rubric: [{ score: 10, label: ">25% EBITDA margin with stability or expansion trend" }, { score: 7, label: "18-25% margin; stable" }, { score: 5, label: "15-18% margin — acceptable for low-risk, stable businesses" }, { score: 3, label: "12-15% margin — below family office standard" }, { score: 0, label: "<12% margin — insufficient for long-term hold economics" }], testGuidance: "Normalize EBITDA for owner compensation and one-time items. Family offices require higher margin thresholds than PE because there's no financial engineering to enhance returns. The margin IS the return.", acceptanceParams: [{ label: "Min EBITDA Margin", defaultValue: ">15% (normalized)", type: "text" }] },
        { name: "Downside Protection", weight: 15, rubric: [{ score: 10, label: "Business survived 2008-2009 and COVID with <15% revenue decline; low leverage; strong liquidity" }, { score: 7, label: "Moderate downturn resilience; <25% revenue decline in worst year; manageable leverage" }, { score: 5, label: "Some cyclicality; >25% revenue decline possible in severe downturn" }, { score: 3, label: "High cyclicality; >40% decline in downturns; leverage amplifies risk" }, { score: 0, label: "Existential risk in downturn; has experienced near-failure in past cycles" }], testGuidance: "Stress-test the business through 2008-2009 and 2020 scenarios. How much did revenue decline? Did the business remain profitable? Could it service debt? Family offices with perpetual hold horizons will see multiple economic cycles — the business must survive all of them.", acceptanceParams: [{ label: "Downturn Resilience", defaultValue: "<25% revenue decline in severe recession", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "financial-summary", label: "Financial Summary (10-year history)" }, { id: "cash-yield-model", label: "Cash Yield at Purchase Price Model" }, { id: "stress-test", label: "Downside Stress Test (2008, 2020 scenarios)" }],
    },
    {
      code: "G5", name: "Management Continuity & Operations", purpose: "Assess management bench depth, succession planning, and the business's ability to operate autonomously under family ownership.", type: "scored", minimumScore: 60, declineThreshold: 40,
      rule: "Weighted composite ≥60.",
      dimensions: [
        { name: "Management Continuity & Succession", weight: 35, rubric: [{ score: 10, label: "Documented succession plan; internal candidates identified and developing; founder transition mapped" }, { score: 7, label: "Succession path exists; #2/#3 capable of stepping up within 12 months" }, { score: 5, label: "No formal succession plan but reasonable management depth" }, { score: 3, label: "Thin management; no succession plan; founder departure would create vacuum" }, { score: 0, label: "Founder IS the management team; no bench; no succession plan" }], testGuidance: "For perpetual hold, the management team will turn over multiple times. Assess: is there a succession plan for the CEO? For the CFO? For key technical roles? A business that can't replace its founder within 12-18 months is a key-person risk, not a portfolio asset.", acceptanceParams: [{ label: "Succession Plan", defaultValue: "Documented plan with named successors", type: "text" }] },
        { name: "Autonomous Operation Capability", weight: 25, rubric: [{ score: 10, label: "Business operates with professional management, formal governance, and independent board" }, { score: 7, label: "Professional management in place; minimal owner involvement needed" }, { score: 5, label: "Management handles daily operations but owner involved in strategy/hiring" }, { score: 3, label: "Owner heavily involved in operations; professional management incomplete" }, { score: 0, label: "Owner runs everything; no professional management infrastructure" }], testGuidance: "Family offices want businesses they can oversee quarterly, not manage daily. Assess whether the business has: a functional CFO/controller, an operations leader, HR infrastructure, IT support, and a quality management system. Missing any of these means the family must fill the gap.", acceptanceParams: [{ label: "Management Completeness", defaultValue: "CEO, CFO, Ops leader in place", type: "text" }] },
        { name: "Systems & Process Maturity", weight: 20, rubric: [{ score: 10, label: "Modern ERP, documented SOPs, financial reporting package, KPI dashboards" }, { score: 7, label: "Adequate systems with minor gaps; reporting is regular and reliable" }, { score: 5, label: "Basic systems in place; reporting requires manual effort" }, { score: 3, label: "Minimal systems; owner manages by intuition rather than data" }, { score: 0, label: "No systems — spreadsheet-based operations with tribal knowledge" }], testGuidance: "Mature systems are essential for remote governance. Family offices need reliable financial reporting, operational dashboards, and documented processes. A business run from the founder's head cannot be governed from the boardroom.", acceptanceParams: [{ label: "Systems Maturity", defaultValue: "ERP in place with monthly financial reporting", type: "text" }] },
        { name: "Integration Simplicity", weight: 20, rubric: [{ score: 10, label: "Standalone operations; only needs governance overlay (board, reporting, compliance)" }, { score: 7, label: "Minor integration needed — reporting alignment, banking, insurance" }, { score: 5, label: "Moderate integration — shared services, compliance framework" }, { score: 3, label: "Significant changes needed to meet family office standards" }, { score: 0, label: "Requires major operational restructuring before family office standards are met" }], testGuidance: "Family offices don't integrate businesses into a platform — they add governance overlay. Assess what changes are needed to bring the business up to the family's reporting, compliance, and governance standards. Less change = lower risk.", acceptanceParams: [{ label: "Governance Needs", defaultValue: "Board formation, quarterly reporting, annual audit", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "management-assessment", label: "Management Team Assessment" }, { id: "succession-plan", label: "Succession Plan Review" }, { id: "governance-plan", label: "Governance Overlay Plan" }],
    },
    {
      code: "G6", name: "Risk Assessment", purpose: "Conservative risk assessment with highest weight on key person risk and long-term sustainability.", type: "scored", minimumScore: 65, declineThreshold: 45,
      rule: "Weighted composite ≥65. Highest risk bar of any template — long hold amplifies every risk.",
      dimensions: [
        { name: "Key Person Risk", weight: 35, rubric: [{ score: 10, label: "No single person critical; deep bench; documented institutional knowledge" }, { score: 7, label: "Key person identified; succession path exists; retention mechanisms in place" }, { score: 5, label: "Some key-person dependency; manageable with transition planning" }, { score: 3, label: "High dependency on 1-2 individuals; succession unclear" }, { score: 0, label: "Single person IS the business; departure = total loss of institutional knowledge" }], testGuidance: "Key person risk is existential for family office investments because the hold period spans decades. One departure early in ownership can destroy the thesis. Assess EVERY person whose departure would materially impact operations, customer relationships, or institutional knowledge.", acceptanceParams: [{ label: "Key Person Analysis", defaultValue: "Departure impact assessment for top 5 individuals", type: "text" }] },
        { name: "Customer Concentration", weight: 25, rubric: [{ score: 10, label: "No customer >10% of revenue; highly diversified" }, { score: 7, label: "Top customer 10-15%; manageable" }, { score: 5, label: "Top customer 15-20%; requires monitoring" }, { score: 3, label: "Top customer 20-30%; loss would impair cash flow" }, { score: 0, label: "Top customer >30%; single loss is existential" }], testGuidance: "Over a 10-20 year hold, customer relationships will change. Concentration risk compounds over time — a 20% customer today could become a 30% customer in 5 years through natural growth. Plan for the worst case.", acceptanceParams: [{ label: "Max Concentration", defaultValue: "No customer >15%", type: "text" }] },
        { name: "Legal & Environmental", weight: 20, rubric: [{ score: 10, label: "Clean legal history; no environmental liabilities; full regulatory compliance" }, { score: 7, label: "Minor legal matters; environmental compliance current" }, { score: 5, label: "Some legal/environmental matters requiring monitoring" }, { score: 3, label: "Material legal or environmental risks" }, { score: 0, label: "Fatal legal or environmental issue" }], testGuidance: "Long hold amplifies legal and environmental risk. Environmental liabilities can emerge decades after acquisition. Ensure thorough environmental due diligence including Phase I/II assessments where applicable.", acceptanceParams: [{ label: "Legal/Environmental", defaultValue: "No material unresolved issues", type: "text" }] },
        { name: "Reputation & Community Impact", weight: 20, rubric: [{ score: 10, label: "Strong community reputation; ESG-positive; aligns with family public image" }, { score: 7, label: "Neutral reputation; no concerns" }, { score: 5, label: "Some reputation risks but manageable" }, { score: 3, label: "Reputation concerns that could embarrass the family" }, { score: 0, label: "Material reputation risk — public association would harm the family's standing" }], testGuidance: "Family offices invest their name alongside their capital. Assess: environmental practices, labor relations, community perception, product safety, litigation history. A profitable business that generates negative headlines is not worth owning.", acceptanceParams: [{ label: "Reputation Check", defaultValue: "No material reputation risks", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "risk-register", label: "Risk Register" }, { id: "succession-risk", label: "Succession Risk Assessment" }, { id: "environmental", label: "Environmental Due Diligence" }],
    },
    {
      code: "G7", name: "Capital Allocation Decision", purpose: "Permanent portfolio decision framework. No exit modeling — assess as a perpetual cash flow stream.", type: "decision", minimumScore: null, declineThreshold: null,
      rule: "Composite ≥65 = ALLOCATE; 50-64 = CONDITIONAL; <50 = PASS. Requires dual authorization from family principal and investment advisor.",
      dimensions: [
        { name: "Cash Flow Quality", weight: 30, rubric: [{ score: 10, label: "Exceptional cash flow: durable, predictable, growing, with minimal reinvestment needs" }, { score: 7, label: "Strong cash flow profile with high distribution capacity" }, { score: 5, label: "Adequate cash flow; some reinvestment required" }, { score: 3, label: "Cash flow is uncertain or requires significant reinvestment" }, { score: 0, label: "Cash flow negative or unsustainable" }], testGuidance: "Synthesize G4 cash flow analysis. Is this a business you would be comfortable owning for 20 years purely for its cash distributions?", acceptanceParams: [] },
        { name: "Portfolio Fit", weight: 25, rubric: [{ score: 10, label: "Perfect fit: diversifies portfolio, aligns with values, strengthens overall position" }, { score: 7, label: "Good fit with clear portfolio benefit" }, { score: 5, label: "Acceptable fit" }, { score: 3, label: "Marginal fit" }, { score: 0, label: "Poor fit" }], testGuidance: "Synthesize G1 portfolio analysis. Does this make the family's overall portfolio stronger, more diversified, and more aligned with long-term goals?", acceptanceParams: [] },
        { name: "Management & Operational Confidence", weight: 25, rubric: [{ score: 10, label: "Exceptional management; autonomous operations; succession plan in place" }, { score: 7, label: "Strong management with clear governance path" }, { score: 5, label: "Adequate management; some improvement needed" }, { score: 3, label: "Management gaps require family attention" }, { score: 0, label: "Unacceptable management risk" }], testGuidance: "Synthesize G5 management assessment. Can you hand this business to a board and check in quarterly? Or will it require daily involvement?", acceptanceParams: [] },
        { name: "Long-Term Risk Profile", weight: 20, rubric: [{ score: 10, label: "All risks identified and manageable over 20-year horizon" }, { score: 7, label: "Risks managed with appropriate mitigants" }, { score: 5, label: "Some residual risks; monitoring required" }, { score: 3, label: "Material unmitigated risks" }, { score: 0, label: "Unacceptable risk for long-term hold" }], testGuidance: "Synthesize G6 risk assessment through a 20-year lens. Will this business still be generating cash in 2046?", acceptanceParams: [] },
      ],
      evidenceArtifacts: [{ id: "allocation-memo", label: "Capital Allocation Memo" }, { id: "composite-scorecard", label: "Composite Scorecard (G0-G7)" }, { id: "perpetual-cash-model", label: "Perpetual Cash Flow Model" }],
    },
  ],
};
