// ═══════════════════════════════════════════════════════════════
// AMP v2 — Growth Equity Template
//
// For growth equity firms investing in high-growth businesses
// (tech-enabled services, marketplaces, fintech, etc.).
// NOT SaaS-specific — general growth investment thesis.
// Focus: growth trajectory, capital efficiency, TAM,
// founding team quality, and path to profitability.
// ═══════════════════════════════════════════════════════════════

export const GROWTH_EQUITY_TEMPLATE = {
  name: "Growth Equity",
  slug: "growth-equity",
  archetype: "growth_equity",
  description: "Methodology for growth equity firms evaluating high-growth businesses across tech-enabled services, marketplaces, and fintech. Emphasizes growth trajectory, capital efficiency, founding team quality, and TAM expansion. Not SaaS-specific.",
  version: "1.0.0",
  isPublished: true,
  isDefault: false,
  authoredBy: "Alio Foundry",
  changeLog: [{ version: "1.0.0", date: "2026-04-03", changes: ["Initial release"] }],

  personaSchema: {
    fields: [
      { key: "investmentStage", label: "Target Company Stage", required: true },
      { key: "targetRevenueRange", label: "Target Revenue Range at Entry", required: true },
      { key: "growthHurdle", label: "Minimum Revenue Growth Expected", required: true },
      { key: "tamRequirement", label: "Minimum TAM Size", required: true },
      { key: "boardSeatRequired", label: "Board Seat Required?", required: true },
    ],
  },

  weightPropagationRules: [
    { condition: "investmentStage === 'Early Growth'", gateCode: "G1", dimensionName: "Founding Team Quality", adjustment: 15, reason: "Early-stage companies are team bets" },
    { condition: "targetRevenueRange === '$50M+'", gateCode: "G4", dimensionName: "Valuation & Entry Price", adjustment: 10, reason: "Larger companies require more valuation discipline" },
    { condition: "tamRequirement === '$5B+'", gateCode: "G2", dimensionName: "TAM Penetration & Expansion", adjustment: 10, reason: "Large TAM requirement demands evidence of expansion path" },
    { condition: "growthHurdle === '40%+'", gateCode: "G4", dimensionName: "Revenue Growth Trajectory", adjustment: 10, reason: "Aggressive growth targets require stronger evidence" },
  ],

  gatesConfig: [
    {
      code: "G0", name: "Universe Qualification", purpose: "Hard filter for growth equity criteria: minimum growth rate, TAM size, technology/IP differentiation.", type: "binary", minimumScore: null, declineThreshold: null,
      rule: "ALL dimensions must pass. Growth equity has strict minimum thresholds.",
      dimensions: [
        { name: "Growth Rate Minimum", weight: 30, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Target must demonstrate >20% revenue CAGR over the trailing 2-3 years. Growth can be organic or a blend of organic + proven expansion strategy. Businesses growing <20% are not growth equity candidates.", acceptanceParams: [{ label: "Min Revenue CAGR", defaultValue: ">20% trailing 2-3 year CAGR", type: "text" }] },
        { name: "TAM Minimum", weight: 25, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Total addressable market must be large enough to support the target's growth trajectory for 5-7 years. A business growing 30% into a $200M TAM will hit saturation. Verify TAM from independent sources, not management estimates.", acceptanceParams: [{ label: "Min TAM", defaultValue: ">$500M total addressable market", type: "text" }] },
        { name: "Technology / IP Differentiation", weight: 25, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Target must have a defensible technology or intellectual property advantage. This can be proprietary software, data assets, network effects, regulatory licenses, or unique operational IP. Commodity businesses without technology moats are excluded from growth equity mandate.", acceptanceParams: [{ label: "Tech Differentiation", defaultValue: "Proprietary technology, data, or IP advantage", type: "text" }] },
        { name: "Size Parameters", weight: 20, rubric: [{ score: 1, label: "Pass" }, { score: 0, label: "Fail" }], testGuidance: "Revenue must fall within the fund's growth equity check size range. Too small = not institutional quality. Too large = limits return potential.", acceptanceParams: [{ label: "Revenue Range", defaultValue: "$10M–$200M", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "growth-screen", label: "Growth Screen Scorecard" }, { id: "tam-analysis", label: "TAM Analysis (Independent Source)" }],
    },
    {
      code: "G1", name: "Growth Thesis Alignment", purpose: "Assess product-market fit, TAM penetration potential, founding team quality, and governance compatibility.", type: "scored", minimumScore: 60, declineThreshold: 40,
      rule: "Weighted composite ≥60 to advance.",
      dimensions: [
        { name: "TAM Penetration & Expansion", weight: 25, rubric: [{ score: 10, label: "<5% TAM penetration with clear expansion vectors (new segments, geographies, products)" }, { score: 7, label: "5-15% penetration with identified expansion opportunities" }, { score: 5, label: "15-30% penetration — growth requires new market entry or product expansion" }, { score: 3, label: "30-50% penetration — growth will decelerate meaningfully" }, { score: 0, label: ">50% penetration — limited growth runway remaining" }], testGuidance: "Calculate the target's current revenue as a percentage of the independently-verified TAM. Low penetration in a large market is the ideal growth equity setup. Assess expansion vectors: can the company grow into adjacent segments, new geographies, or new products?", acceptanceParams: [{ label: "Current Penetration", defaultValue: "<15% of addressable market", type: "text" }] },
        { name: "Product-Market Fit Evidence", weight: 25, rubric: [{ score: 10, label: "Exceptional PMF: organic demand pull, word-of-mouth growth, high NPS, low churn, rapid adoption" }, { score: 7, label: "Strong PMF: growing customer base, positive unit economics, expanding use cases" }, { score: 5, label: "Moderate PMF: customers like the product but adoption requires sales effort" }, { score: 3, label: "Early PMF: some traction but not yet self-sustaining" }, { score: 0, label: "No PMF: growth is marketing-driven, not demand-driven" }], testGuidance: "Product-market fit is the foundation of growth equity investing. Look for evidence of organic demand: inbound leads, word-of-mouth referrals, expanding usage within existing accounts, customer willingness to reference. Paid-only growth is not PMF.", acceptanceParams: [{ label: "PMF Evidence", defaultValue: "Multiple indicators of organic demand pull", type: "text" }] },
        { name: "Founding Team Quality", weight: 30, rubric: [{ score: 10, label: "Exceptional founder/CEO with relevant domain expertise, proven scaling experience, and strong leadership team" }, { score: 7, label: "Strong founder with good team; capable of scaling from current stage to 3-5x" }, { score: 5, label: "Capable founder but team gaps exist; needs key hires to scale" }, { score: 3, label: "Founder is a technical expert but not a scaling CEO; leadership upgrade needed" }, { score: 0, label: "Weak leadership; founder is an obstacle to scaling" }], testGuidance: "The founding team is the #1 investment criterion in growth equity. Assess: domain expertise, prior scaling experience, ability to attract talent, board relationship quality, coachability, and self-awareness about their gaps. A great market with a weak team is not investable.", acceptanceParams: [{ label: "Team Assessment", defaultValue: "Founder reference calls + track record analysis", type: "text" }] },
        { name: "Governance & Board Rights", weight: 20, rubric: [{ score: 10, label: "Clean cap table; board seat available; standard protective provisions; no problematic prior investors" }, { score: 7, label: "Reasonable governance; board observer or seat; standard minority protections" }, { score: 5, label: "Governance requires negotiation; complex cap table but resolvable" }, { score: 3, label: "Problematic governance: super-voting, no board seat, limited information rights" }, { score: 0, label: "Unacceptable governance: no visibility, no influence, adverse investor dynamics" }], testGuidance: "Growth equity investors need governance rights to protect their investment and influence strategy. Assess: board composition, voting structure, information rights, anti-dilution provisions, and existing investor dynamics. Complex cap tables with misaligned prior investors are a red flag.", acceptanceParams: [{ label: "Board Seat", defaultValue: "Board seat or observer seat required", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "thesis-memo", label: "Growth Thesis Memo" }, { id: "founder-assessment", label: "Founding Team Assessment" }, { id: "tam-analysis", label: "TAM Penetration Analysis" }],
    },
    {
      code: "G2", name: "Market & Competitive Position", purpose: "Assess market size, competitive dynamics, and the target's ability to sustain growth through competitive moats.", type: "scored", minimumScore: 65, declineThreshold: 45,
      rule: "Weighted composite ≥65. Growth equity requires large, expanding markets.",
      dimensions: [
        { name: "Market Growth Rate", weight: 25, rubric: [{ score: 10, label: ">20% market CAGR with structural tailwinds (technology adoption, regulatory, demographic)" }, { score: 7, label: "10-20% CAGR with clear growth drivers" }, { score: 5, label: "5-10% growth — acceptable if target is gaining share" }, { score: 3, label: "<5% market growth — target must be a share-taker" }, { score: 0, label: "Flat or declining market" }], testGuidance: "Growth equity requires market tailwinds. The best investments are in growing markets where the target grows faster than the market. Source market growth from independent research, not management projections.", acceptanceParams: [{ label: "Min Market CAGR", defaultValue: ">10%", type: "text" }] },
        { name: "Target Market Position", weight: 20, rubric: [{ score: 10, label: "Category leader or #1-2 in defined segment with strong brand" }, { score: 7, label: "Top-5 player with differentiated positioning and growing share" }, { score: 5, label: "Established player with competitive product" }, { score: 3, label: "Emerging player — product is competitive but market position is unproven" }, { score: 0, label: "Late entrant with no differentiation" }], testGuidance: "Assess competitive positioning: market share trends, win rates, brand awareness, customer preference data. Growth equity investments should be in companies gaining share, not defending it.", acceptanceParams: [{ label: "Market Position", defaultValue: "Top-5 and gaining share", type: "text" }] },
        { name: "Network Effects & Switching Costs", weight: 30, rubric: [{ score: 10, label: "Strong network effects + high switching costs — product becomes more valuable with each user and is deeply embedded in workflows" }, { score: 7, label: "Meaningful switching costs; customers would face significant disruption to switch" }, { score: 5, label: "Moderate stickiness; some switching costs but alternatives exist" }, { score: 3, label: "Low switching costs; customer retention depends on product quality alone" }, { score: 0, label: "No switching costs; commodity product; churn risk is high" }], testGuidance: "The best growth equity investments have compounding competitive advantages. Network effects (each user makes the product more valuable) and switching costs (leaving is painful) create durable moats. Assess both independently.", acceptanceParams: [{ label: "Moat Assessment", defaultValue: "At least one durable competitive advantage", type: "text" }] },
        { name: "Competitive Intensity", weight: 25, rubric: [{ score: 10, label: "Blue ocean — limited direct competition; target has clear differentiation" }, { score: 7, label: "Manageable competition; target has defensible advantages" }, { score: 5, label: "Competitive market but target is differentiated in its segment" }, { score: 3, label: "Intense competition; multiple well-funded competitors" }, { score: 0, label: "Hyper-competitive with larger, better-funded competitors" }], testGuidance: "Map the competitive landscape including venture-backed competitors. Assess: how much capital has been raised by competitors? Are there well-funded insurgents? Is the market consolidating? Competition for talent is also a signal of market intensity.", acceptanceParams: [{ label: "Competitor Landscape", defaultValue: "Map top 5 competitors with funding status", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "market-map", label: "Market Landscape Map" }, { id: "competitive-analysis", label: "Competitive Analysis" }, { id: "moat-assessment", label: "Competitive Moat Assessment" }],
    },
    {
      code: "G3", name: "Business Model & Scalability", purpose: "Assess business model scalability, unit economics health, and go-to-market efficiency.", type: "scored", minimumScore: 50, declineThreshold: 35,
      rule: "Weighted composite ≥50. Lower bar — growth businesses are still proving their model.",
      dimensions: [
        { name: "Revenue Model Scalability", weight: 30, rubric: [{ score: 10, label: "Highly scalable: incremental revenue has near-zero marginal cost; strong operating leverage" }, { score: 7, label: "Good scalability with moderate operating leverage" }, { score: 5, label: "Linear scalability — revenue grows proportional to cost" }, { score: 3, label: "Sublinear scalability — growth requires proportional or greater cost increases" }, { score: 0, label: "Not scalable — every dollar of revenue requires equivalent cost investment" }], testGuidance: "Assess operating leverage: does each incremental dollar of revenue drop through at higher margin than the prior dollar? Strong scalability means gross margins expand as revenue grows. Technology businesses typically have the highest scalability.", acceptanceParams: [{ label: "Gross Margin Trend", defaultValue: "Expanding or stable >50%", type: "text" }] },
        { name: "GTM Efficiency", weight: 25, rubric: [{ score: 10, label: "Highly efficient GTM: strong inbound, low CAC, short sales cycles, high conversion rates" }, { score: 7, label: "Efficient GTM with room to optimize; proven customer acquisition channels" }, { score: 5, label: "Average GTM efficiency; sales-heavy with reasonable payback" }, { score: 3, label: "Inefficient GTM; high CAC relative to LTV; long payback periods" }, { score: 0, label: "Broken GTM; burning cash to acquire low-value customers" }], testGuidance: "Assess go-to-market efficiency through multiple lenses: customer acquisition cost, sales cycle length, conversion rates, channel mix (inbound vs. outbound), and payback period. An efficient GTM engine is the foundation of sustainable growth.", acceptanceParams: [{ label: "CAC Payback", defaultValue: "<18 months", type: "text" }] },
        { name: "Customer Economics", weight: 25, rubric: [{ score: 10, label: "Exceptional unit economics: LTV/CAC >5x; gross margins >70%; expanding account value" }, { score: 7, label: "Strong unit economics: LTV/CAC >3x; healthy margins; stable customer value" }, { score: 5, label: "Acceptable unit economics: LTV/CAC 2-3x; margins need improvement" }, { score: 3, label: "Weak unit economics: LTV/CAC <2x; margins under pressure" }, { score: 0, label: "Negative unit economics; losing money on each customer" }], testGuidance: "Calculate lifetime value vs. customer acquisition cost at a cohort level. Are newer cohorts performing better or worse than older ones? Expanding LTV/CAC is the strongest signal of a healthy growth business.", acceptanceParams: [{ label: "LTV/CAC Ratio", defaultValue: ">3x", type: "text" }] },
        { name: "Expansion & Upsell Potential", weight: 20, rubric: [{ score: 10, label: "Strong expansion motion: net revenue retention >120%; clear upsell/cross-sell paths" }, { score: 7, label: "Good expansion: net retention >110%; some upsell capability" }, { score: 5, label: "Moderate expansion: net retention ~100%; limited upsell today" }, { score: 3, label: "Flat expansion: net retention <100%; customers not growing" }, { score: 0, label: "Contraction: net retention <90%; losing customer value over time" }], testGuidance: "Assess the company's ability to grow revenue from existing customers through upsell, cross-sell, and usage expansion. Net revenue retention above 100% means the business grows even without adding new customers.", acceptanceParams: [{ label: "Net Revenue Retention", defaultValue: ">110%", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "unit-economics", label: "Unit Economics Dashboard" }, { id: "gtm-analysis", label: "GTM Efficiency Analysis" }],
    },
    {
      code: "G4", name: "Financial Profile & Valuation", purpose: "Financial analysis focused on growth trajectory, capital efficiency, and entry valuation relative to growth rate.", type: "scored", minimumScore: 55, declineThreshold: 35,
      rule: "Weighted composite ≥55 to advance.",
      dimensions: [
        { name: "Revenue Growth Trajectory", weight: 25, rubric: [{ score: 10, label: ">40% revenue CAGR with accelerating or stable growth trajectory" }, { score: 7, label: "25-40% growth with clear sustainability drivers" }, { score: 5, label: "15-25% growth — acceptable but decelerating" }, { score: 3, label: "10-15% growth — below growth equity threshold" }, { score: 0, label: "<10% growth or declining trajectory" }], testGuidance: "Analyze revenue growth over 3+ years. Is growth accelerating, stable, or decelerating? Decompose growth into new customer acquisition vs. expansion from existing customers. Sustainable growth comes from both vectors.", acceptanceParams: [{ label: "Revenue CAGR", defaultValue: ">20% trailing 3-year", type: "text" }] },
        { name: "Unit Economics & Margins", weight: 25, rubric: [{ score: 10, label: "Gross margin >70% with expanding contribution margins; clear path to 20%+ EBITDA margin at scale" }, { score: 7, label: "Gross margin >60%; contribution margins positive and improving" }, { score: 5, label: "Gross margin >50%; contribution margins near breakeven" }, { score: 3, label: "Gross margin <50%; contribution margins negative" }, { score: 0, label: "Gross margin <40% or deteriorating; no path to profitability" }], testGuidance: "Assess margin structure at gross, contribution, and operating levels. Growth businesses may be unprofitable at the EBITDA level, but gross margins and contribution margins should be healthy and improving. A clear path to profitability must exist.", acceptanceParams: [{ label: "Gross Margin", defaultValue: ">60%", type: "text" }] },
        { name: "Capital Efficiency", weight: 20, rubric: [{ score: 10, label: "Capital-efficient growth: <$0.50 of capital consumed per $1 of new revenue generated" }, { score: 7, label: "Moderate efficiency: $0.50-$1.00 per $1 of new revenue" }, { score: 5, label: "Capital-intensive growth: $1.00-$1.50 per $1 of new revenue" }, { score: 3, label: "Inefficient: $1.50-$2.50 per $1 of new revenue" }, { score: 0, label: "Highly inefficient: >$2.50 per $1 of new revenue — burning cash" }], testGuidance: "Calculate the burn multiple: net burn / net new revenue. Lower is better. Capital-efficient businesses create more value per dollar invested. Also assess: how much of the invested capital has gone to product development vs. sales/marketing vs. G&A?", acceptanceParams: [{ label: "Burn Multiple", defaultValue: "<1.5x", type: "text" }] },
        { name: "Valuation & Entry Price", weight: 20, rubric: [{ score: 10, label: "Entry valuation at significant discount to comparable growth companies; <3x EV/Revenue for 30%+ grower" }, { score: 7, label: "Fair valuation for growth rate; EV/Revenue multiple justified by growth trajectory" }, { score: 5, label: "Full valuation; requires continued execution to justify entry price" }, { score: 3, label: "Premium valuation; limited margin of safety if growth decelerates" }, { score: 0, label: "Excessive valuation; priced for perfection with no room for deceleration" }], testGuidance: "Compare valuation to public and private comps at similar growth rates. The growth-adjusted multiple (EV/Revenue divided by growth rate) normalizes across different growth profiles. <0.5x is attractive; >1.0x is expensive.", acceptanceParams: [{ label: "Growth-Adjusted Multiple", defaultValue: "<0.5x (EV/Rev ÷ Revenue Growth %)", type: "text" }] },
        { name: "Path to Profitability", weight: 10, rubric: [{ score: 10, label: "Already profitable or clear line of sight to profitability within 12 months" }, { score: 7, label: "Path to profitability within 18-24 months with identified levers" }, { score: 5, label: "Profitability achievable in 2-3 years with disciplined execution" }, { score: 3, label: "Profitability unclear; requires significant scale or business model changes" }, { score: 0, label: "No credible path to profitability" }], testGuidance: "Every growth equity investment must have a path to profitability. Assess: at what revenue level does the business break even? What margin improvements are needed? How realistic is the timeline? Growth without a path to profitability is a red flag.", acceptanceParams: [{ label: "Breakeven Timeline", defaultValue: "<24 months to EBITDA breakeven", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "financial-model", label: "Growth Financial Model" }, { id: "unit-economics", label: "Unit Economics Analysis" }, { id: "valuation-comps", label: "Valuation Comparables (Public + Private)" }],
    },
    {
      code: "G5", name: "Governance & Growth Infrastructure", purpose: "Assess board governance, growth infrastructure, and follow-on capital needs.", type: "scored", minimumScore: 50, declineThreshold: 35,
      rule: "Weighted composite ≥50. Lower bar — growth companies build infrastructure as they scale.",
      dimensions: [
        { name: "Board Composition & Governance", weight: 30, rubric: [{ score: 10, label: "Professional board with relevant operating experience; clear information rights; aligned incentive structure" }, { score: 7, label: "Functional board; some gaps in experience but receptive to growth investor input" }, { score: 5, label: "Founder-dominated board; willing to add independent directors" }, { score: 3, label: "Weak governance; founder maintains disproportionate control" }, { score: 0, label: "No functional board; founder makes all decisions without external input" }], testGuidance: "Assess board composition, meeting cadence, information package quality, and decision-making process. Growth equity investors typically add a board seat and expect quarterly board meetings with detailed financial and operational reporting.", acceptanceParams: [{ label: "Board Seat", defaultValue: "Board seat for lead investor", type: "text" }] },
        { name: "Follow-On Investment Rights", weight: 25, rubric: [{ score: 10, label: "Pro-rata rights secured; anti-dilution protection; clear path for follow-on capital" }, { score: 7, label: "Standard protective provisions with reasonable pro-rata rights" }, { score: 5, label: "Basic protections; some negotiation needed on follow-on terms" }, { score: 3, label: "Limited protections; complex investor dynamics may block follow-on" }, { score: 0, label: "No follow-on rights; at risk of dilution in future rounds" }], testGuidance: "Growth equity investments often require follow-on capital. Assess: pro-rata rights, anti-dilution provisions, information rights for future rounds, and investor dynamics that could impact follow-on participation.", acceptanceParams: [{ label: "Pro-Rata Rights", defaultValue: "Full pro-rata on future rounds", type: "text" }] },
        { name: "Operational Infrastructure", weight: 25, rubric: [{ score: 10, label: "Mature operational infrastructure: financial systems, HR, legal, IT, security — all scaled" }, { score: 7, label: "Adequate infrastructure; scaling well; 1-2 areas need improvement" }, { score: 5, label: "Basic infrastructure; several areas need investment to support next phase" }, { score: 3, label: "Minimal infrastructure; company has outgrown its operational setup" }, { score: 0, label: "No infrastructure; company operating on duct tape and spreadsheets" }], testGuidance: "Growth businesses often underinvest in operational infrastructure. Assess: financial reporting quality, HR processes, IT security, legal/compliance maturity, and data infrastructure. These investments are necessary for sustainable scaling.", acceptanceParams: [{ label: "Infra Maturity", defaultValue: "Monthly financial close + GAAP reporting", type: "text" }] },
        { name: "Talent & Hiring Capacity", weight: 20, rubric: [{ score: 10, label: "Strong employer brand; efficient recruiting; leadership team can attract top talent" }, { score: 7, label: "Good hiring track record; able to fill key roles within reasonable timeframes" }, { score: 5, label: "Hiring is a challenge; competing with larger companies for talent" }, { score: 3, label: "Struggling to hire; key roles unfilled; founder doing too many jobs" }, { score: 0, label: "Talent crisis; losing employees to competitors; cannot fill critical roles" }], testGuidance: "Scaling requires hiring. Assess: open roles, time-to-fill for key positions, employee satisfaction (Glassdoor, pulse surveys), management depth, and the company's ability to attract experienced operators. Growth without talent is unsustainable.", acceptanceParams: [{ label: "Key Hires Needed", defaultValue: "Identify critical open roles", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "governance-summary", label: "Governance & Board Summary" }, { id: "cap-table", label: "Cap Table Analysis" }],
    },
    {
      code: "G6", name: "Risk Assessment", purpose: "Growth-specific risks including technology debt, founder dependency, and market timing.", type: "scored", minimumScore: 55, declineThreshold: 35,
      rule: "Weighted composite ≥55.",
      dimensions: [
        { name: "Technology Risk / Technical Debt", weight: 25, rubric: [{ score: 10, label: "Modern tech stack; minimal technical debt; engineering team is strong and productive" }, { score: 7, label: "Manageable technical debt; planned remediation; good engineering culture" }, { score: 5, label: "Moderate technical debt; some legacy systems; reliability concerns" }, { score: 3, label: "Significant technical debt; frequent outages; engineering velocity declining" }, { score: 0, label: "Critical technical debt; platform instability; would require rewrite" }], testGuidance: "Conduct a technical due diligence assessment. Key areas: code quality, test coverage, deployment frequency, incident rate, scalability architecture, security posture, and engineering team retention. Technical debt is a hidden liability that can derail growth.", acceptanceParams: [{ label: "Tech DD", defaultValue: "Independent technical due diligence completed", type: "text" }] },
        { name: "Founding Team Dependency", weight: 25, rubric: [{ score: 10, label: "Strong leadership team beyond founders; company can execute without any single person" }, { score: 7, label: "Founders are important but team is capable; succession paths exist" }, { score: 5, label: "Some founder dependency but mitigated by team depth in key areas" }, { score: 3, label: "High founder dependency; company culture and direction are founder-defined" }, { score: 0, label: "Founder IS the company; departure would trigger customer/employee exodus" }], testGuidance: "Growth equity invests in companies, not just founders. Assess: would the business continue to grow if the CEO took a 6-month sabbatical? Is there a COO/President who owns execution? Can the CTO/VPE ship product without founder involvement?", acceptanceParams: [{ label: "Founder Dependency", defaultValue: "Business can operate 3+ months without founder", type: "text" }] },
        { name: "Customer Concentration", weight: 20, rubric: [{ score: 10, label: "Highly diversified; no customer >5% of revenue" }, { score: 7, label: "Low concentration; top customer <10%" }, { score: 5, label: "Moderate concentration; top customer 10-20%" }, { score: 3, label: "High concentration; top customer >20%" }, { score: 0, label: "Extreme concentration; >30% from one customer" }], testGuidance: "Standard concentration analysis. Growth businesses can have higher concentration if the customer base is growing rapidly, but any single customer >15% is a risk flag.", acceptanceParams: [{ label: "Max Concentration", defaultValue: "No customer >15%", type: "text" }] },
        { name: "Market Timing Risk", weight: 15, rubric: [{ score: 10, label: "Market is early/mid-adoption — significant runway remaining" }, { score: 7, label: "Market is growing steadily; competition increasing but manageable" }, { score: 5, label: "Market may be peaking; growth rate starting to moderate" }, { score: 3, label: "Late in market cycle; growth opportunities narrowing" }, { score: 0, label: "Market is saturated or commoditizing" }], testGuidance: "Assess where we are in the market adoption cycle. Growth equity investors need 5-7 years of growth runway. If the market is already in late-stage adoption, returns will compress regardless of execution quality.", acceptanceParams: [{ label: "Adoption Stage", defaultValue: "Early or mid-adoption", type: "text" }] },
        { name: "Legal & IP Risk", weight: 15, rubric: [{ score: 10, label: "Clean IP ownership; no material litigation; full compliance" }, { score: 7, label: "Minor legal matters; IP well-documented and assigned" }, { score: 5, label: "Some IP ambiguity; minor litigation" }, { score: 3, label: "Material IP disputes or litigation" }, { score: 0, label: "Fatal legal or IP issue" }], testGuidance: "Review: patent portfolio, trade secrets, employee IP assignment agreements, open source compliance, data privacy (GDPR/CCPA), and any pending litigation. IP ownership issues can invalidate the entire investment thesis.", acceptanceParams: [{ label: "IP/Legal Check", defaultValue: "Clean IP ownership confirmed", type: "text" }] },
      ],
      evidenceArtifacts: [{ id: "tech-dd", label: "Technical Due Diligence Report" }, { id: "risk-register", label: "Risk Register" }, { id: "ip-review", label: "IP & Legal Review" }],
    },
    {
      code: "G7", name: "Investment Decision", purpose: "Synthesize all gate outputs into an investment recommendation with explicit returns modeling and follow-on capital planning.", type: "decision", minimumScore: null, declineThreshold: null,
      rule: "Composite ≥65 = INVEST; 50-64 = CONDITIONAL; <50 = PASS. IC requires dual authorization.",
      dimensions: [
        { name: "Growth Attractiveness", weight: 30, rubric: [{ score: 10, label: "Exceptional: large TAM, strong PMF, durable moat, high-quality team — best-in-class opportunity" }, { score: 7, label: "Strong growth thesis with manageable risks" }, { score: 5, label: "Acceptable growth profile" }, { score: 3, label: "Below average growth characteristics" }, { score: 0, label: "Not a growth equity opportunity" }], testGuidance: "Synthesize G1 + G2: TAM, PMF, team, moat, competitive dynamics. Would you invest based solely on the growth thesis?", acceptanceParams: [] },
        { name: "Financial Attractiveness", weight: 25, rubric: [{ score: 10, label: "Compelling entry valuation with clear path to >3x MOIC in base case" }, { score: 7, label: "Reasonable entry with >2.5x MOIC achievable" }, { score: 5, label: "Full valuation; >2x MOIC requires strong execution" }, { score: 3, label: "Expensive; limited margin of safety" }, { score: 0, label: "Overvalued relative to growth and risk profile" }], testGuidance: "Synthesize G4 financial analysis. Model returns under base, upside, and downside scenarios. What entry multiple makes this a good investment? Is the proposed price below that level?", acceptanceParams: [] },
        { name: "Risk-Adjusted Confidence", weight: 25, rubric: [{ score: 10, label: "All key risks identified and mitigated; high confidence in execution" }, { score: 7, label: "Manageable risks with reasonable mitigation plans" }, { score: 5, label: "Some residual risks requiring monitoring" }, { score: 3, label: "Material risks that could impair returns" }, { score: 0, label: "Unacceptable risk profile" }], testGuidance: "Synthesize G6 risks. What is the probability of losing >50% of capital? What are the top 3 risks and how confident are you in the mitigation plans?", acceptanceParams: [] },
        { name: "Follow-On Capital Needs", weight: 20, rubric: [{ score: 10, label: "Company is self-funding or needs minimal follow-on; strong governance protections in place" }, { score: 7, label: "One follow-on round expected; pro-rata rights secured; capital available" }, { score: 5, label: "Multiple rounds needed; follow-on capital requirements are manageable" }, { score: 3, label: "Significant follow-on needs; risk of dilution if performance slips" }, { score: 0, label: "Cash-hungry business with uncertain follow-on financing availability" }], testGuidance: "Model the company's capital needs through profitability. How many more rounds of funding are needed? What is the total capital commitment including follow-on? What happens if the company can't raise additional capital?", acceptanceParams: [] },
      ],
      evidenceArtifacts: [{ id: "ic-memo", label: "IC Memo (Final)" }, { id: "returns-model", label: "Returns Model (Base/Up/Down)" }, { id: "composite-scorecard", label: "Composite Scorecard (G0-G7)" }],
    },
  ],
};
